lzc-sdk-version: "0.1"
name: PDFMathTranslate
package: cloud.lazycat.app.pdf-math-translate
version: 1.9.6
description: 一个用于 PDF 科学论文的翻译工具，旨在保留文档的排版格式。
homepage: https://github.com/Byaidu/PDFMathTranslate
author: Byaidu
application:
  subdomain: pdf-math-translate
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://pdfmt:7860/
services:
  pdfmt:
    container_name: pdfmt
    image: docker.hlmirror.com/byaidu/pdf2zh:1.9.6
    binds:
      - /lzcapp/var/input:/input
      - /lzcapp/var/output:/output
